# Imersão de Pandas - Teo Me Why

### Breve revisão de Python - Turbo

#### Strings

#### Numéricos

#### Listas
* list comprehension

#### Dicionários

#### If, Else, Elif

#### For & While

#### Funções

## Finalmente, Pandas!!

Fingindo um pouco a análise de dados

### Comandos básicos

* Importação da biblioteca
* O que são Series e Dataframes?
    - Criando o primeiro dataframe
* Leitura de arquivos
* Escrita de arquivos
* Operações básicas de DataFrame

In [1]:
import time

In [2]:
for i in range(10):
    time.sleep(1)

In [3]:
import pandas as pd

In [6]:
numeros = [1,2,3,4,5]
num_serie = pd.Series(numeros)

In [10]:
numeros

[1, 2, 3, 4, 5]

In [14]:
numeros[0]

1

In [23]:
numeros.append(1)

In [19]:
num_serie.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [20]:
idade = pd.Series([28,29,31,18,17,22], name="idades")

In [21]:
idade

0    28
1    29
2    31
3    18
4    17
5    22
Name: idades, dtype: int64

In [22]:
idade.name

'idades'

In [24]:
nome = ["Téo", "Nah", "Lara", "Vag", "Pedro", "Maria"]
nome_serie = pd.Series( nome, name="nomes" )
nome_serie

0      Téo
1      Nah
2     Lara
3      Vag
4    Pedro
5    Maria
Name: nomes, dtype: object

In [25]:
nome_serie.describe()

count         6
unique        6
top       Maria
freq          1
Name: nomes, dtype: object

In [27]:
# Nome da séries (s.name)
nome_serie.name

'nomes'

In [28]:
nome_serie.index

RangeIndex(start=0, stop=6, step=1)

In [29]:
nome_serie.shape

(6,)

In [30]:
nome = ['Teo', 'Nah', 'Lara', 'Pedro', 'José']
idade = [28, 30, 27, 25, 22]

In [35]:
df_1 = pd.DataFrame() # cria DataFrame sem dados

df_1["nome"] = nome   # Define um campo (coluna, variável) de nome
df_1["idade"] = idade # Define um campo (coluna, variável) de idade
df_1["altura"] = [182, 165, 170, 176, 187] # Cria variável de altura

df_1

    nome  idade  altura
0    Teo     28     182
1    Nah     30     165
2   Lara     27     170
3  Pedro     25     176
4   José     22     187

In [36]:
df_1.describe()

          idade      altura
count   5.00000    5.000000
mean   26.40000  176.000000
std     3.04959    8.860023
min    22.00000  165.000000
25%    25.00000  170.000000
50%    27.00000  176.000000
75%    28.00000  182.000000
max    30.00000  187.000000

In [38]:
data = {
    "nome": ["Téo", "Nah", "Pedro", "Lara", "José"],
    "idade": [28, 30, 32, 27, 31],
    "altura": [182, 169, 174, 165, 187]
}

df_data = pd.DataFrame( data )
df_data

    nome  idade  altura
0    Téo     28     182
1    Nah     30     169
2  Pedro     32     174
3   Lara     27     165
4   José     31     187

### Importando dados de um arquivo

In [40]:
df_votacao = pd.read_csv("data/votacao_agg_estado.csv") # importa de um arquivo csv
df_votacao

/home/teo/anaconda3/envs/twitch/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680
2,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DOS TRABALHADORES,13,PT,GOVERNADOR,DEFERIDO,APTO,JOSE RICARDO WENDLING,...,0,0,0,0,0,0,0,0,0,181257
3,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO HUMANISTA DA SOLIDARIEDADE,31,PHS,GOVERNADOR,DEFERIDO,APTO,MAURICIO WILKER DE AZEVEDO BARRETO,...,0,0,0,0,0,0,0,0,0,22623
4,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PATRIA LIVRE,54,PPL,GOVERNADOR,DEFERIDO,APTO,JADELVONE NOGUEIRA DELTRUDES,...,0,0,0,0,0,0,0,0,0,3362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511100,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,MARCOS JOSE ROCHA DOS SANTOS,...,0,0,0,0,0,0,0,0,0,530188
511101,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,ANTONIO CARLOS VALADARES FILHO,...,0,0,0,0,0,0,0,0,0,370161
511102,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,JOAO ALBERTO RODRIGUES CAPIBERIBE,...,0,0,0,0,0,0,0,0,0,174540
511103,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,0,20497480
511104,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,0,451329,0,0,0,451329

In [43]:
df_bens = pd.read_excel("data/tb_bens.xlsx") # Importa um arquivo xlsx (excel)

df_bens

,ano_eleicao,codigo_eleicao,codigo_tipo_eleicao,data_eleicao,descricao_eleicao,nome_tipo_eleicao,nome_ue,sigla_ue,sigla_uf,numero_sequencial,codigo_tipo,data_ultima_atualizacao,descricao_tipo,detalhe,hora_ultima_atualizacao,numero_ordem,valor
0,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000001,32,12/07/2018,QUOTAS OU QUINHOES DE CAPITAL,8360 QUOTAS DE CAPITAL SOCIAL DA EMPRESA MARMU...,16:36:00,1,8360.00
1,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000001,21,12/07/2018,"VEICULO AUTOMOTOR TERRESTRE: CAMINHAO, AUTOMOV...","AUTOMOVEL HILUX CD,",16:36:00,2,143000.00
2,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000058,21,12/07/2018,"VEICULO AUTOMOTOR TERRESTRE: CAMINHAO, AUTOMOV...","CAMINHAO MERCEDES-BENZ, MODELO 2726, ANO 2010",16:36:00,2,150000.00
3,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000001,45,12/07/2018,"APLICACAO DE RENDA FIXA (CDB, RDB E OUTROS)",POUPEX BANCO DO BRASIL,16:36:00,3,148.84
4,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000001,61,12/07/2018,DEPOSITO BANCARIO EM CONTA CORRENTE NO PAIS,SALDO EM CONTA BANCARIA (BANCO DO BRASIL),16:36:00,4,937.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176316,2018,297,2,07/10/2018,ELEICOES GERAIS ESTADUAIS 2018,ELEICAO ORDINARIA,TOCANTINS,TO,TO,270000629137,32,13/12/2018,QUOTAS OU QUINHOES DE CAPITAL,"QUOTAS DE CAPITAL SOCIAL NA EMPRESA TERRAPLAN,...",17:02:46,1,126667.00
176317,2018,297,2,07/10/2018,ELEICOES GERAIS ESTADUAIS 2018,ELEICAO ORDINARIA,TOCANTINS,TO,TO,270000629137,32,13/12/2018,QUOTAS OU QUINHOES DE CAPITAL,QUOTAS DE CAPITAL SOCIAL NA EMPRESA FAROL EMP...,17:02:46,2,25000.00
176318,2018,297,2,07/10/2018,ELEICOES GERAIS ESTADUAIS 2018,ELEICAO ORDINARIA,TOCANTINS,TO,TO,270000629137,97,13/12/2018,VGBL - VIDA GERADOR DE BENEFICIO LIVRE,"SALDO EM APLICACOES JUNTO AO BANCO BRADESCO, VGBL",17:02:46,3,265783.16
176319,2018,297,2,07/10/2018,ELEICOES GERAIS ESTADUAIS 2018,ELEICAO ORDINARIA,TOCANTINS,TO,TO,270000629137,79,13/12/2018,OUTROS FUNDOS,DISPONIBILIDADES DE RESGATES DE APLICACOES E A...,17:02:46,4,1200000.00
176320,2018,297,2,07/10/2018,ELEICOES GERAIS ESTADUAIS 2018,ELEICAO ORDINARIA,TOCANTINS,TO,TO,270000629137,41,13/12/2018,CADERNETA DE POUPANCA,SALDO EM CADERNETA DE POUPANCA JUNTO AO BANCO ...,17:02:46,5,30239.10

In [47]:
df_votacao.head() # retorna as 5 primeiras linhas do dataset

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680
2,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DOS TRABALHADORES,13,PT,GOVERNADOR,DEFERIDO,APTO,JOSE RICARDO WENDLING,...,0,0,0,0,0,0,0,0,0,181257
3,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO HUMANISTA DA SOLIDARIEDADE,31,PHS,GOVERNADOR,DEFERIDO,APTO,MAURICIO WILKER DE AZEVEDO BARRETO,...,0,0,0,0,0,0,0,0,0,22623
4,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PATRIA LIVRE,54,PPL,GOVERNADOR,DEFERIDO,APTO,JADELVONE NOGUEIRA DELTRUDES,...,0,0,0,0,0,0,0,0,0,3362

In [46]:
df_votacao.head(10) # Retorna as 10 primeiras linhas do dataset

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680
2,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DOS TRABALHADORES,13,PT,GOVERNADOR,DEFERIDO,APTO,JOSE RICARDO WENDLING,...,0,0,0,0,0,0,0,0,0,181257
3,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO HUMANISTA DA SOLIDARIEDADE,31,PHS,GOVERNADOR,DEFERIDO,APTO,MAURICIO WILKER DE AZEVEDO BARRETO,...,0,0,0,0,0,0,0,0,0,22623
4,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PATRIA LIVRE,54,PPL,GOVERNADOR,DEFERIDO,APTO,JADELVONE NOGUEIRA DELTRUDES,...,0,0,0,0,0,0,0,0,0,3362
5,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO POPULAR SOCIALISTA,23,PPS,GOVERNADOR,INDEFERIDO COM RECURSO,APTO,LILIANE ARAUJO DE ALMEIDA,...,0,0,0,0,0,0,0,0,0,0
6,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PROGRESSISTA,11,PP,GOVERNADOR,SUBSTITUTO PENDENTE DE JULGAMENTO,APTO,REBECCA MARTINS GARCIA,...,0,0,0,0,0,0,0,0,0,268922
7,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,DEFERIDO,APTO,MARCELO AUGUSTO DA EIRA CORREA,...,0,0,0,0,0,0,0,0,0,18877
8,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,REDE SUSTENTABILIDADE,18,REDE,GOVERNADOR,DEFERIDO,APTO,LUIZ CASTRO ANDRADE NETO,...,0,0,0,0,0,0,0,0,0,39240
9,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,2,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,782933

In [53]:
df_votacao.tail(10) # últimas linhas

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
511095,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL CRISTAO,20,PSC,GOVERNADOR,APTO,NaN,WILSON MIRANDA LIMA,...,0,0,0,0,0,0,0,0,0,2067908
511096,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL DEMOCRATICO,55,PSD,GOVERNADOR,APTO,NaN,BELIVALDO CHAGAS SILVA,...,0,0,0,0,0,0,0,0,0,679051
511097,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL DEMOCRATICO,55,PSD,GOVERNADOR,APTO,NaN,GELSON LUIZ MERISIO,...,0,0,0,0,0,0,0,0,2150484,2150484
511098,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,ANTONIO OLIVERIO GARCIA DE ALMEIDA,...,0,0,0,0,0,0,0,136612,0,136612
511099,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,CARLOS MOISES DA SILVA,...,0,0,0,0,0,0,0,0,5288358,5288358
511100,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,MARCOS JOSE ROCHA DOS SANTOS,...,0,0,0,0,0,0,0,0,0,530188
511101,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,ANTONIO CARLOS VALADARES FILHO,...,0,0,0,0,0,0,0,0,0,370161
511102,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,JOAO ALBERTO RODRIGUES CAPIBERIBE,...,0,0,0,0,0,0,0,0,0,174540
511103,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,0,20497480
511104,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,0,451329,0,0,0,451329

In [ ]:
df = pd.DataFrame()
df.head() # cabeçalho
df.tail() # Final

In [50]:
# Dimensoes do dataframe
df_votacao.shape

(511105, 43)

In [51]:
# Quais são suas colunas?
df_votacao.columns

Index(['ano_eleicao', 'descricao_eleicao', 'numero_turno', 'nome_partido',
       'numero_partido', 'sigla_partido', 'descricao_cargo',
       'descricao_situacao_candidatura',
       'descricao_situacao_candidatura_superior', 'nome', 'nome_social',
       'nome_urna', 'numero_sequencial', 'numero_urna', 'total_votos_ac',
       'total_votos_al', 'total_votos_am', 'total_votos_ap', 'total_votos_ba',
       'total_votos_rj', 'total_votos_sp', 'total_votos_ce', 'total_votos_ro',
       'total_votos_se', 'total_votos_pr', 'total_votos_mg', 'total_votos_mt',
       'total_votos_pe', 'total_votos_pb', 'total_votos_zz', 'total_votos_go',
       'total_votos_rs', 'total_votos_rn', 'total_votos_to', 'total_votos_pa',
       'total_votos_ms', 'total_votos_pi', 'total_votos_ma', 'total_votos_df',
       'total_votos_es', 'total_votos_rr', 'total_votos_sc', 'total_votos'],
      dtype='object')

In [54]:
# Quais são os indices
df_votacao.index

RangeIndex(start=0, stop=511105, step=1)

## Utilitários

In [56]:
df_votacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 511105 entries, 0 to 511104
Data columns (total 43 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   ano_eleicao                              511105 non-null  int64
 1   descricao_eleicao                        511105 non-null  object
 2   numero_turno                             511105 non-null  int64
 3   nome_partido                             511105 non-null  object
 4   numero_partido                           511105 non-null  int64
 5   sigla_partido                            511105 non-null  object
 6   descricao_cargo                          511105 non-null  object
 7   descricao_situacao_candidatura           511105 non-null  object
 8   descricao_situacao_candidatura_superior  484655 non-null  object
 9   nome                                     511105 non-null  object
 10  nome_social                              0 non-null       float64
 11  nome_urna                                511095 non-null  object
 12  numero_sequencial                        511105 non-null  int64
 13  numero_urna                              511105 non-null  int64
 14  total_votos_ac                           511105 non-null  int64
 15  total_votos_al                           511105 non-null  int64
 16  total_votos_am                           511105 non-null  int64
 17  total_votos_ap                           511105 non-null  int64
 18  total_votos_ba                           511105 non-null  int64
 19  total_votos_rj                           511105 non-null  int64
 20  total_votos_sp                           511105 non-null  int64
 21  total_votos_ce                           511105 non-null  int64
 22  total_votos_ro                           511105 non-null  int64
 23  total_votos_se                           511105 non-null  int64
 24  total_votos_pr                           511105 non-null  int64
 25  total_votos_mg                           511105 non-null  int64
 26  total_votos_mt                           511105 non-null  int64
 27  total_votos_pe                           511105 non-null  int64
 28  total_votos_pb                           511105 non-null  int64
 29  total_votos_zz                           511105 non-null  int64
 30  total_votos_go                           511105 non-null  int64
 31  total_votos_rs                           511105 non-null  int64
 32  total_votos_rn                           511105 non-null  int64
 33  total_votos_to                           511105 non-null  int64
 34  total_votos_pa                           511105 non-null  int64
 35  total_votos_ms                           511105 non-null  int64
 36  total_votos_pi                           511105 non-null  int64
 37  total_votos_ma                           511105 non-null  int64
 38  total_votos_df                           511105 non-null  int64
 39  total_votos_es                           511105 non-null  int64
 40  total_votos_rr                           511105 non-null  int64
 41  total_votos_sc                           511105 non-null  int64
 42  total_votos                              511105 non-null  int64
dtypes: float64(1), int64(34), object(8)
memory usage: 167.7+ MB

In [60]:
tipos_campos = df_votacao.dtypes

In [62]:
tipos_campos

ano_eleicao                                  int64
descricao_eleicao                           object
numero_turno                                 int64
nome_partido                                object
numero_partido                               int64
sigla_partido                               object
descricao_cargo                             object
descricao_situacao_candidatura              object
descricao_situacao_candidatura_superior     object
nome                                        object
nome_social                                float64
nome_urna                                   object
numero_sequencial                            int64
numero_urna                                  int64
total_votos_ac                               int64
total_votos_al                               int64
total_votos_am                               int64
total_votos_ap                               int64
total_votos_ba                               int64
total_votos_rj                               int64
total_votos_sp                               int64
total_votos_ce                               int64
total_votos_ro                               int64
total_votos_se                               int64
total_votos_pr                               int64
total_votos_mg                               int64
total_votos_mt                               int64
total_votos_pe                               int64
total_votos_pb                               int64
total_votos_zz                               int64
total_votos_go                               int64
total_votos_rs                               int64
total_votos_rn                               int64
total_votos_to                               int64
total_votos_pa                               int64
total_votos_ms                               int64
total_votos_pi                               int64
total_votos_ma                               int64
total_votos_df                               int64
total_votos_es                               int64
total_votos_rr                               int64
total_votos_sc                               int64
total_votos                                  int64
dtype: object

## Navegação pelo DataFrame

In [65]:
df_votacao["sigla_partido"] # Acesso uma coluna (Série)

0          PDT
1         PMDB
2           PT
3          PHS
4          PPL
          ...
511100     PSL
511101     PSB
511102     PSB
511103     PSB
511104     PSB
Name: sigla_partido, Length: 511105, dtype: object

In [69]:
df_votacao["nome_urna"] # Retorna uma Séries

0             AMAZONINO MENDES
1                EDUARDO BRAGA
2                 JOSE RICARDO
3               WILKER BARRETO
4                       JARDEL
                  ...
511100    CORONEL MARCOS ROCHA
511101         VALADARES FILHO
511102                 CAPI 40
511103           MARCIO FRANCA
511104      RODRIGO ROLLEMBERG
Name: nome_urna, Length: 511105, dtype: object

In [68]:
df_votacao[ ["sigla_partido", "nome_urna"] ] # Acessando mais de uma coluna (DataFrame)

       sigla_partido             nome_urna
0                PDT      AMAZONINO MENDES
1               PMDB         EDUARDO BRAGA
2                 PT          JOSE RICARDO
3                PHS        WILKER BARRETO
4                PPL                JARDEL
...              ...                   ...
511100           PSL  CORONEL MARCOS ROCHA
511101           PSB       VALADARES FILHO
511102           PSB               CAPI 40
511103           PSB         MARCIO FRANCA
511104           PSB    RODRIGO ROLLEMBERG

[511105 rows x 2 columns]

In [71]:
df_votacao.head(1)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397

In [72]:
df_votacao.loc[0] # Acessa uma linha

ano_eleicao                                                             2014
descricao_eleicao                          ELEICAO SUPLEMENTAR GOVERNADOR AM
numero_turno                                                               1
nome_partido                                 PARTIDO DEMOCRATICO TRABALHISTA
numero_partido                                                            12
sigla_partido                                                            PDT
descricao_cargo                                                   GOVERNADOR
descricao_situacao_candidatura                                      DEFERIDO
descricao_situacao_candidatura_superior                                 APTO
nome                                                AMAZONINO ARMANDO MENDES
nome_social                                                              NaN
nome_urna                                                   AMAZONINO MENDES
numero_sequencial                                                40000012067
numero_urna                                                               12
total_votos_ac                                                             0
total_votos_al                                                             0
total_votos_am                                                        577397
total_votos_ap                                                             0
total_votos_ba                                                             0
total_votos_rj                                                             0
total_votos_sp                                                             0
total_votos_ce                                                             0
total_votos_ro                                                             0
total_votos_se                                                             0
total_votos_pr                                                             0
total_votos_mg                                                             0
total_votos_mt                                                             0
total_votos_pe                                                             0
total_votos_pb                                                             0
total_votos_zz                                                             0
total_votos_go                                                             0
total_votos_rs                                                             0
total_votos_rn                                                             0
total_votos_to                                                             0
total_votos_pa                                                             0
total_votos_ms                                                             0
total_votos_pi                                                             0
total_votos_ma                                                             0
total_votos_df                                                             0
total_votos_es                                                             0
total_votos_rr                                                             0
total_votos_sc                                                             0
total_votos                                                           577397
Name: 0, dtype: object

In [77]:
df_votacao.loc[ [0,1,5] ] # Navegando por linhas

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680
5,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO POPULAR SOCIALISTA,23,PPS,GOVERNADOR,INDEFERIDO COM RECURSO,APTO,LILIANE ARAUJO DE ALMEIDA,...,0,0,0,0,0,0,0,0,0,0

In [80]:
df_votacao[ ["nome_urna", "sigla_partido"] ].loc[ [0,10,25,25000] ]

              nome_urna sigla_partido
0      AMAZONINO MENDES           PDT
10        EDUARDO BRAGA          PMDB
25                JESSE           DEM
25000          PR. ALEX           DEM

In [84]:
df_votacao["nome_urna"][25000]

'PR. ALEX'

In [83]:
df_votacao['sigla_partido'][0]  # Define a coluna e a index a ser usado

'PDT'

## Filtros

* Comparações lógicas de ==, >, >=, <, <=, !=
* isna()
* isin()

In [96]:
df_1["idade_30_mais"] = df_1["idade"] >= 30

df_1

    nome  idade  altura  idade_30_mais
0    Teo     28     182          False
1    Nah     30     165           True
2   Lara     27     170          False
3  Pedro     25     176          False
4   José     22     187          False

In [98]:
df_1[ df_1["idade_30_mais"] ]

  nome  idade  altura  idade_30_mais
1  Nah     30     165           True

In [100]:
filtro_25_menos = df_1["idade"] <= 25 # Isso retorna um "vetor" (Série de True e False)

filtro_25_menos

0    False
1    False
2    False
3     True
4     True
Name: idade, dtype: bool

In [101]:
df_1[filtro_25_menos]

    nome  idade  altura  idade_30_mais
3  Pedro     25     176          False
4   José     22     187          False

In [102]:
filtro_2018 = df_votacao["ano_eleicao"] == 2018

In [ ]:
df_votacao_2018 = df_votacao[filtro_2018] # Filtra e retorna a referência das linhas filtradas

In [120]:
df_votacao_2018 = df_votacao[filtro_2018].copy() # Filtra e retorna uma cópia das linhas filtradas

df_votacao_2018["Teo"] = 1

In [122]:
df_votacao_2018

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,Teo
484655,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,NaN,JOSE MARIA EYMAEL,...,1413,325,551,776,822,792,116,859,41710,1
484656,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,NaN,HENRIQUE DE CAMPOS MEIRELLES,...,100724,18154,16761,52214,26939,22232,3426,51670,1288950,1
484657,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,NaN,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,229122,90897,47974,50654,53640,79049,19231,154068,5096350,1
484658,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,NaN,CIRO FERREIRA GOMES,...,415593,112296,211240,282472,266272,195553,14838,264312,13344371,1
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511100,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,MARCOS JOSE ROCHA DOS SANTOS,...,0,0,0,0,0,0,0,0,530188,1
511101,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,ANTONIO CARLOS VALADARES FILHO,...,0,0,0,0,0,0,0,0,370161,1
511102,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,JOAO ALBERTO RODRIGUES CAPIBERIBE,...,0,0,0,0,0,0,0,0,174540,1
511103,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,20497480,1
511104,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,451329,0,0,0,451329,1

In [125]:
filtro_psdb = df_votacao["sigla_partido"] == "PSDB"
df_psdb = df_votacao[filtro_psdb].copy()
df_psdb

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
2715,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO DISTRITAL,DEFERIDO,APTO,AILTON RIBEIRO DA SILVA,...,0,0,0,0,0,500,0,0,0,500
2716,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO DISTRITAL,DEFERIDO,APTO,ANA MARIA DA SILVA,...,0,0,0,0,0,160,0,0,0,160
2717,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO DISTRITAL,DEFERIDO,APTO,ANTONIO AUGUSTO DE FREITAS JUNCAL,...,0,0,0,0,0,747,0,0,0,747
2718,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO DISTRITAL,DEFERIDO,APTO,ANTONIO CARLOS FERREIRA RAMOS,...,0,0,0,0,0,300,0,0,0,300
2719,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO DISTRITAL,DEFERIDO,APTO,CARMEN SOARES MARTINS JANCOSKI,...,0,0,0,0,0,97,0,0,0,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511083,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,GOVERNADOR,APTO,NaN,EDUARDO FIGUEIREDO CAVALHEIRO LEITE,...,0,0,0,0,0,0,0,0,0,6256634
511084,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,GOVERNADOR,APTO,NaN,EXPEDITO GONCALVES FERREIRA JUNIOR,...,0,0,0,0,0,0,0,0,0,269032
511085,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,GOVERNADOR,APTO,NaN,JOAO AGRIPINO DA COSTA DORIA JUNIOR,...,0,0,0,0,0,0,0,0,0,21980700
511086,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,GOVERNADOR,APTO,NaN,JOSE DE ANCHIETA JUNIOR,...,0,0,0,0,0,0,0,119489,0,119489
511087,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,GOVERNADOR,APTO,NaN,REINALDO AZAMBUJA SILVA,...,0,0,677310,0,0,0,0,0,0,677310

In [128]:
df_votacao[df_votacao["descricao_cargo"] == "PRESIDENTE"]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
686,2014,ELEICOES GERAIS 2014,1,PARTIDO COMUNISTA BRASILEIRO,21,PCB,PRESIDENTE,DEFERIDO,APTO,MAURO LUIS IASI,...,261,833,390,487,1151,559,723,71,1413,47845
1501,2014,ELEICOES GERAIS 2014,1,PARTIDO DA CAUSA OPERARIA,29,PCO,PRESIDENTE,DEFERIDO,APTO,RUI COSTA PIMENTA,...,44,207,97,151,158,473,215,48,390,12324
3684,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,DEFERIDO,APTO,AECIO NEVES DA CUNHA,...,203183,1058334,558826,242256,365655,570494,694085,109070,1963772,34897211
6969,2014,ELEICOES GERAIS 2014,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,DEFERIDO,APTO,DILMA VANA ROUSSEFF,...,368431,2040981,507063,1235337,2187864,363861,653839,82942,1141102,43267668
10912,2014,ELEICOES GERAIS 2014,1,PARTIDO RENOVADOR TRABALHISTA BRASILEIRO,28,PRTB,PRESIDENTE,DEFERIDO,APTO,JOSE LEVY FIDELIX DA CRUZ,...,1654,11501,4623,2338,6707,15270,9021,1285,15774,446878
13637,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIAL CRISTAO,20,PSC,PRESIDENTE,DEFERIDO,APTO,EVERALDO DIAS PEREIRA,...,4740,43068,6977,6284,22389,10053,16138,5194,23661,780513
14311,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIAL DEMOCRATA CRISTAO,27,PSDC,PRESIDENTE,DEFERIDO,APTO,JOSE MARIA EYMAEL,...,221,915,478,752,2205,1295,1133,515,2005,61250
16700,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,PRESIDENTE,DEFERIDO,APTO,LUCIANA KREBS GENRO,...,2875,40353,10708,10159,13100,31435,19016,2815,53532,1612186
17897,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,PRESIDENTE,DEFERIDO,APTO,MARIA OSMARINA MARINA DA SILVA VAZ DE LIMA,...,150690,627319,257976,246271,535013,565279,567964,47087,476430,22176619
18134,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO,16,PSTU,PRESIDENTE,DEFERIDO,APTO,JOSE MARIA DE ALMEIDA,...,247,3012,977,1456,4340,1495,1313,209,3975,91209
21898,2014,ELEICOES GERAIS 2014,1,PARTIDO VERDE,43,PV,PRESIDENTE,DEFERIDO,APTO,EDUARDO JORGE MARTINS ALVES SOBRINHO,...,1430,12260,4093,4385,6965,19478,11875,780,30239,630099
22402,2014,ELEICOES GERAIS 2014,2,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,DEFERIDO,APTO,AECIO NEVES DA CUNHA,...,292176,1561066,762797,384157,667823,946171,1065485,139752,2472142,51041155
22416,2014,ELEICOES GERAIS 2014,2,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,DEFERIDO,APTO,DILMA VANA ROUSSEFF,...,428774,2104151,590965,1385265,2475985,582354,912391,97425,1354775,54501118
484655,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,NaN,JOSE MARIA EYMAEL,...,242,1413,325,551,776,822,792,116,859,41710
484656,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,NaN,HENRIQUE DE CAMPOS MEIRELLES,...,5324,100724,18154,16761,52214,26939,22232,3426,51670,1288950
484657,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,NaN,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,21666,229122,90897,47974,50654,53640,79049,19231,154068,5096350
484658,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,NaN,CIRO FERREIRA GOMES,...,54262,415593,112296,211240,282472,266272,195553,14838,264312,13344371
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,311212,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051
484660,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO NOVO,30,NOVO,PRESIDENTE,APTO,NaN,JOAO DIONISIO FILGUEIRA BARRETO AMOEDO,...,7113,28314,26491,15308,17233,44879,44306,4309,158562,2679745
484661,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO PATRIA LIVRE,54,PPL,PRESIDENTE,APTO,NaN,JOAO VICENTE FONTELLA GOULART,...,160,1009,319,280,412,700,533,69,923,30176
484662,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,337782,1499294,769116,346944,817531,936494,1122131,174306,2603665,49277010
484663,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,PRESIDENTE,APTO,NaN,GUILHERME CASTRO BOULOS,...,2764,32417,6174,6145,16016,13177,8358,2443,21484,617122
484664,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO,16,PSTU,PRESIDENTE,APTO,NaN,VERA LUCIA PEREIRA DA SILVA SALGADO,...,251,2391,623,850,2842,908,711,146,1686,55762
484665,2018,ELEICAO GERAL FEDERAL 2018,1,PATRIOTA,51,PATRI,PRESIDENTE,APTO,NaN,BENEVENUTO DACIOLO FONSECA DOS SANTOS,...,6284,51547,14337,12212,34204,26925,41734,2928,22392,1348323
484666,2018,ELEICAO GERAL FEDERAL 2018,1,PODEMOS,19,PODE,PRESIDENTE,APTO,NaN,ALVARO FERNANDES DIAS,...,2471,12407,12527,5218,6320,11138,11352,1472,51771,859601
484667,2018,ELEICAO GERAL FEDERAL 2018,1,REDE SUSTENTABILIDADE,18,REDE,PRESIDENTE,APTO,NaN,MARIA OSMARINA MARINA DA SILVA VAZ DE LIMA,...,7229,53682,12279,13313,23635,32115,26529,4098,25813,1069578
484668,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,743186,4225538,930050,2834226,4857826,926680,1495536,145744,1881448,94081812
484669,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,713368,3484376,1744098,844190,1773130,2160822,2553222,366536,5932484,115595694

In [132]:
filtro_2018_pres = (df_votacao["ano_eleicao"] == 2018) & (df_votacao["descricao_cargo"] == "PRESIDENTE")
df_2018_pres = df_votacao[filtro_2018_pres]
df_2018_pres

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
484655,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,NaN,JOSE MARIA EYMAEL,...,242,1413,325,551,776,822,792,116,859,41710
484656,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,NaN,HENRIQUE DE CAMPOS MEIRELLES,...,5324,100724,18154,16761,52214,26939,22232,3426,51670,1288950
484657,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,NaN,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,21666,229122,90897,47974,50654,53640,79049,19231,154068,5096350
484658,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,NaN,CIRO FERREIRA GOMES,...,54262,415593,112296,211240,282472,266272,195553,14838,264312,13344371
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,311212,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051
484660,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO NOVO,30,NOVO,PRESIDENTE,APTO,NaN,JOAO DIONISIO FILGUEIRA BARRETO AMOEDO,...,7113,28314,26491,15308,17233,44879,44306,4309,158562,2679745
484661,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO PATRIA LIVRE,54,PPL,PRESIDENTE,APTO,NaN,JOAO VICENTE FONTELLA GOULART,...,160,1009,319,280,412,700,533,69,923,30176
484662,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,337782,1499294,769116,346944,817531,936494,1122131,174306,2603665,49277010
484663,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,PRESIDENTE,APTO,NaN,GUILHERME CASTRO BOULOS,...,2764,32417,6174,6145,16016,13177,8358,2443,21484,617122
484664,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO,16,PSTU,PRESIDENTE,APTO,NaN,VERA LUCIA PEREIRA DA SILVA SALGADO,...,251,2391,623,850,2842,908,711,146,1686,55762
484665,2018,ELEICAO GERAL FEDERAL 2018,1,PATRIOTA,51,PATRI,PRESIDENTE,APTO,NaN,BENEVENUTO DACIOLO FONSECA DOS SANTOS,...,6284,51547,14337,12212,34204,26925,41734,2928,22392,1348323
484666,2018,ELEICAO GERAL FEDERAL 2018,1,PODEMOS,19,PODE,PRESIDENTE,APTO,NaN,ALVARO FERNANDES DIAS,...,2471,12407,12527,5218,6320,11138,11352,1472,51771,859601
484667,2018,ELEICAO GERAL FEDERAL 2018,1,REDE SUSTENTABILIDADE,18,REDE,PRESIDENTE,APTO,NaN,MARIA OSMARINA MARINA DA SILVA VAZ DE LIMA,...,7229,53682,12279,13313,23635,32115,26529,4098,25813,1069578
484668,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,743186,4225538,930050,2834226,4857826,926680,1495536,145744,1881448,94081812
484669,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,713368,3484376,1744098,844190,1773130,2160822,2553222,366536,5932484,115595694

In [139]:
filtro_idade_altura = (df_1["idade"] >= 25) & (df_1["altura"] >= 175)
df_1[filtro_idade_altura]

    nome  idade  altura  idade_30_mais
0    Teo     28     182          False
3  Pedro     25     176          False

In [143]:
# Quantos candidatos à presidência tivemos em 2018?

filtro_2018_pres = (df_votacao["ano_eleicao"] == 2018) & (df_votacao["descricao_cargo"] == "PRESIDENTE")
df_2018_pres = df_votacao[filtro_2018_pres].copy()

df_2018_pres

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
484655,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,NaN,JOSE MARIA EYMAEL,...,242,1413,325,551,776,822,792,116,859,41710
484656,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,NaN,HENRIQUE DE CAMPOS MEIRELLES,...,5324,100724,18154,16761,52214,26939,22232,3426,51670,1288950
484657,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,NaN,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,21666,229122,90897,47974,50654,53640,79049,19231,154068,5096350
484658,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,NaN,CIRO FERREIRA GOMES,...,54262,415593,112296,211240,282472,266272,195553,14838,264312,13344371
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,311212,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051
484660,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO NOVO,30,NOVO,PRESIDENTE,APTO,NaN,JOAO DIONISIO FILGUEIRA BARRETO AMOEDO,...,7113,28314,26491,15308,17233,44879,44306,4309,158562,2679745
484661,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO PATRIA LIVRE,54,PPL,PRESIDENTE,APTO,NaN,JOAO VICENTE FONTELLA GOULART,...,160,1009,319,280,412,700,533,69,923,30176
484662,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,337782,1499294,769116,346944,817531,936494,1122131,174306,2603665,49277010
484663,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,PRESIDENTE,APTO,NaN,GUILHERME CASTRO BOULOS,...,2764,32417,6174,6145,16016,13177,8358,2443,21484,617122
484664,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO,16,PSTU,PRESIDENTE,APTO,NaN,VERA LUCIA PEREIRA DA SILVA SALGADO,...,251,2391,623,850,2842,908,711,146,1686,55762
484665,2018,ELEICAO GERAL FEDERAL 2018,1,PATRIOTA,51,PATRI,PRESIDENTE,APTO,NaN,BENEVENUTO DACIOLO FONSECA DOS SANTOS,...,6284,51547,14337,12212,34204,26925,41734,2928,22392,1348323
484666,2018,ELEICAO GERAL FEDERAL 2018,1,PODEMOS,19,PODE,PRESIDENTE,APTO,NaN,ALVARO FERNANDES DIAS,...,2471,12407,12527,5218,6320,11138,11352,1472,51771,859601
484667,2018,ELEICAO GERAL FEDERAL 2018,1,REDE SUSTENTABILIDADE,18,REDE,PRESIDENTE,APTO,NaN,MARIA OSMARINA MARINA DA SILVA VAZ DE LIMA,...,7229,53682,12279,13313,23635,32115,26529,4098,25813,1069578
484668,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,743186,4225538,930050,2834226,4857826,926680,1495536,145744,1881448,94081812
484669,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,713368,3484376,1744098,844190,1773130,2160822,2553222,366536,5932484,115595694

In [146]:
df_2018_pres["nome_urna"].nunique()

13

In [147]:
df_2018_pres["nome_urna"].unique()

array(['EYMAEL', 'HENRIQUE MEIRELLES', 'GERALDO ALCKMIN', 'CIRO GOMES',
       'FERNANDO HADDAD', 'JOAO AMOEDO', 'JOAO GOULART FILHO',
       'JAIR BOLSONARO', 'GUILHERME BOULOS', 'VERA', 'CABO DACIOLO',
       'ALVARO DIAS', 'MARINA SILVA'], dtype=object)

In [148]:
df_2018_pres["sigla_partido"].unique()

array(['DC', 'MDB', 'PSDB', 'PDT', 'PT', 'NOVO', 'PPL', 'PSL', 'PSOL',
       'PSTU', 'PATRI', 'PODE', 'REDE'], dtype=object)

#### Valores nulos

In [162]:
filtro_na = df_votacao["descricao_situacao_candidatura_superior"].isna()

df_votacao[~filtro_na] # Nega o filtro

df_votacao[filtro_na] # Pega só os NANs

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
484655,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,NaN,JOSE MARIA EYMAEL,...,242,1413,325,551,776,822,792,116,859,41710
484656,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,NaN,HENRIQUE DE CAMPOS MEIRELLES,...,5324,100724,18154,16761,52214,26939,22232,3426,51670,1288950
484657,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,NaN,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,21666,229122,90897,47974,50654,53640,79049,19231,154068,5096350
484658,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,NaN,CIRO FERREIRA GOMES,...,54262,415593,112296,211240,282472,266272,195553,14838,264312,13344371
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,311212,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511100,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,MARCOS JOSE ROCHA DOS SANTOS,...,0,0,0,0,0,0,0,0,0,530188
511101,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,ANTONIO CARLOS VALADARES FILHO,...,0,0,0,0,0,0,0,0,0,370161
511102,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,JOAO ALBERTO RODRIGUES CAPIBERIBE,...,0,0,0,0,0,0,0,0,0,174540
511103,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,0,20497480
511104,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,0,451329,0,0,0,451329

## Renomeando Colunas

In [152]:
df_1 = df_1.rename(columns = { "idade_30_mais": "idade_+30"})

In [153]:
df_1

    nome  idade  altura  idade_+30
0    Teo     28     182      False
1    Nah     30     165       True
2   Lara     27     170      False
3  Pedro     25     176      False
4   José     22     187      False

In [165]:
# Ordenando as colunas do DataFrame

colunas_ordem = ["nome", "idade", "idade_+30", "altura"]

df_1 = df_1[ colunas_ordem ].copy()
df_1

    nome  idade  idade_+30  altura
0    Teo     28      False     182
1    Nah     30       True     165
2   Lara     27      False     170
3  Pedro     25      False     176
4   José     22      False     187

## Transformações, conversões e remoções

* Operações com escalares
* Operações entre colunas
* apply()
* funções anônimas

In [166]:
df_1["dobro_da_idade"] = df_1["idade"] * 2

df_1

    nome  idade  idade_+30  altura  dobro_da_idade
0    Teo     28      False     182              56
1    Nah     30       True     165              60
2   Lara     27      False     170              54
3  Pedro     25      False     176              50
4   José     22      False     187              44

In [167]:
df_1["soma_idade_altura"] = df_1["idade"] + df_1["altura"]
df_1

    nome  idade  idade_+30  altura  dobro_da_idade  soma_idade_altura
0    Teo     28      False     182              56                210
1    Nah     30       True     165              60                195
2   Lara     27      False     170              54                197
3  Pedro     25      False     176              50                201
4   José     22      False     187              44                209

In [169]:
import numpy as np

In [176]:
df_1["log_soma_idade_altura"] = np.log( df_1["soma_idade_altura"] )
df_1

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura
0,Teo,28,False,182,56,210,5.347108
1,Nah,30,True,165,60,195,5.273000
2,Lara,27,False,170,54,197,5.283204
3,Pedro,25,False,176,50,201,5.303305
4,José,22,False,187,44,209,5.342334

In [177]:
df_1["Nome Completo"] = ["Teodoro Calvo",
                         "Natalia Ataide",
                         "Lara Calvo",
                         "Pedro Silva",
                         "José Siqueira"]

df_1

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura,Nome Completo
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide
2,Lara,27,False,170,54,197,5.283204,Lara Calvo
3,Pedro,25,False,176,50,201,5.303305,Pedro Silva
4,José,22,False,187,44,209,5.342334,José Siqueira

In [178]:
"Téo Calvo".split(" ")

['Téo', 'Calvo']

In [182]:
def pega_sobrenome(nome_completo):
    nome_split = nome_completo.split()
    sobrenome = nome_split[-1]
    return sobrenome

In [184]:
pega_sobrenome("Teodoro Balbino Calvo")

'Calvo'

In [187]:
for i in df_1["Nome Completo"]:
    print(pega_sobrenome(i))

Calvo
Ataide
Calvo
Silva
Siqueira

In [189]:
df_1["sobrenome"] = df_1["Nome Completo"].apply( pega_sobrenome )
df_1

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura,Nome Completo,sobrenome
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide,Ataide
2,Lara,27,False,170,54,197,5.283204,Lara Calvo,Calvo
3,Pedro,25,False,176,50,201,5.303305,Pedro Silva,Silva
4,José,22,False,187,44,209,5.342334,José Siqueira,Siqueira

In [ ]:
df[coluna1] + df[coluna2]

In [ ]:
df[coluna].apply()

In [190]:
def soma(a, b):
    return a + b

In [191]:
soma(20,30)

50

In [194]:
soma_lambda = lambda a,b: a+b

In [195]:
soma_lambda(20, 30)

50

In [197]:
def nome_upper(nome):
    return nome.upper()

In [199]:
df_1["nome"].apply(nome_upper)

0      TEO
1      NAH
2     LARA
3    PEDRO
4     JOSÉ
Name: nome, dtype: object

In [201]:
df_1["nome_upper"] = df_1["nome"].apply( lambda x: x.upper() )
df_1

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura,Nome Completo,sobrenome,nome_upper
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo,TEO
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide,Ataide,NAH
2,Lara,27,False,170,54,197,5.283204,Lara Calvo,Calvo,LARA
3,Pedro,25,False,176,50,201,5.303305,Pedro Silva,Silva,PEDRO
4,José,22,False,187,44,209,5.342334,José Siqueira,Siqueira,JOSÉ

## Group by & Sort by

* Operações Estatísticas: sum, mean, count, std...
* Agrupando por chave

In [207]:
df_1

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura,Nome Completo,sobrenome,nome_upper
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo,TEO
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide,Ataide,NAH
2,Lara,27,False,170,54,197,5.283204,Lara Calvo,Calvo,LARA
3,Pedro,25,False,176,50,201,5.303305,Pedro Silva,Silva,PEDRO
4,José,22,False,187,44,209,5.342334,José Siqueira,Siqueira,JOSÉ

In [206]:
df_1.groupby(by=["sobrenome"])["idade"].describe().T

sobrenome  Ataide      Calvo  Silva  Siqueira
count         1.0   2.000000    1.0       1.0
mean         30.0  27.500000   25.0      22.0
std           NaN   0.707107    NaN       NaN
min          30.0  27.000000   25.0      22.0
25%          30.0  27.250000   25.0      22.0
50%          30.0  27.500000   25.0      22.0
75%          30.0  27.750000   25.0      22.0
max          30.0  28.000000   25.0      22.0

In [209]:
df_1.groupby(by=["sobrenome"])[["idade", "altura"]].mean()

           idade  altura
sobrenome
Ataide      30.0   165.0
Calvo       27.5   176.0
Silva       25.0   176.0
Siqueira    22.0   187.0

In [ ]:
df.groupby()

In [213]:
df_ano_partido = df_votacao.groupby( by=["ano_eleicao","sigla_partido"] )[["nome_urna"]].nunique()

In [218]:
df_ano_partido = df_ano_partido.reset_index()
df_ano_partido = df_ano_partido.rename(columns={"nome_urna": "qtde_candidatos"})
df_ano_partido

     ano_eleicao  sigla_partido  qtde_candidatos
0           2014            DEM              576
1           2014        PC DO B              780
2           2014            PCB              109
3           2014            PCO               27
4           2014            PDT              941
..           ...            ...              ...
99          2018            PTB              597
100         2018            PTC              758
101         2018             PV              829
102         2018           REDE              778
103         2018  SOLIDARIEDADE              735

[104 rows x 3 columns]

In [222]:
df_ano_partido = df_ano_partido.sort_values(by=["ano_eleicao", "qtde_candidatos"], ascending=[True, False])

In [225]:
df_ano_partido[ df_ano_partido["ano_eleicao"] == 2018]

     ano_eleicao  sigla_partido  qtde_candidatos
95          2018            PSL             1407
96          2018           PSOL             1198
98          2018             PT             1180
74          2018          PATRI             1122
88          2018           PROS             1024
72          2018            MDB             1004
69          2018         AVANTE              959
79          2018            PHS              925
89          2018            PRP              896
90          2018           PRTB              886
78          2018            PDT              884
91          2018            PSB              859
82          2018           PODE              858
94          2018           PSDB              847
101         2018             PV              829
92          2018            PSC              806
87          2018            PRB              798
102         2018           REDE              778
100         2018            PTC              758
75          2018        PC DO B              749
103         2018  SOLIDARIEDADE              735
70          2018             DC              707
83          2018             PP              696
81          2018            PMN              690
86          2018             PR              663
93          2018            PSD              648
71          2018            DEM              631
85          2018            PPS              625
99          2018            PTB              597
84          2018            PPL              539
80          2018            PMB              401
73          2018           NOVO              391
97          2018           PSTU              139
77          2018            PCO               76
76          2018            PCB               62

## Stack e Unstack

* Empilhando e desempilhando dados

In [227]:
df_ano_partido = df_votacao.groupby( by=["ano_eleicao","sigla_partido"] )[["nome_urna"]].nunique()
df_ano_partido

                           nome_urna
ano_eleicao sigla_partido
2014        DEM                  576
            PC DO B              780
            PCB                  109
            PCO                   27
            PDT                  941
...                              ...
2018        PTB                  597
            PTC                  758
            PV                   829
            REDE                 778
            SOLIDARIEDADE        735

[104 rows x 1 columns]

In [228]:
df_ano_partido.unstack()

              nome_urna                                                  \
sigla_partido    AVANTE     DC      DEM     MDB   NOVO   PATRI  PC DO B
ano_eleicao
2014                NaN    NaN    576.0     NaN    NaN     NaN    780.0
2016                NaN    NaN  17978.0     NaN  137.0     NaN  10526.0
2018              959.0  707.0    631.0  1004.0  391.0  1122.0    749.0

                                     ...                                   \
sigla_partido    PCB   PCO      PDT  ...   PSTU       PT PT DO B      PTB
ano_eleicao                          ...
2014           109.0  27.0    941.0  ...  246.0   1218.0   691.0    847.0
2016           206.0  53.0  21455.0  ...  264.0  19322.0  6650.0  18652.0
2018            62.0  76.0    884.0  ...  139.0   1180.0     NaN    597.0


sigla_partido     PTC     PTN       PV    REDE       SD SOLIDARIEDADE
ano_eleicao
2014            686.0   553.0    963.0     1.0    491.0           NaN
2016           7809.0  8552.0  14579.0  3477.0  12913.0           NaN
2018            758.0     NaN    829.0   778.0      NaN         735.0

[3 rows x 41 columns]

In [ ]:
df.stack()
df.unstack()
df.explode()

In [230]:
df_1["empregos"] = [ ["boti", "via", 'gc'], ["vila casa", "maria pia"], ["sutiod artes", "construtora"], [], []  ]
df_1

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura,Nome Completo,sobrenome,nome_upper,empregos
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo,TEO,"[boti, via, gc]"
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide,Ataide,NAH,"[vila casa, maria pia]"
2,Lara,27,False,170,54,197,5.283204,Lara Calvo,Calvo,LARA,"[sutiod artes, construtora]"
3,Pedro,25,False,176,50,201,5.303305,Pedro Silva,Silva,PEDRO,[]
4,José,22,False,187,44,209,5.342334,José Siqueira,Siqueira,JOSÉ,[]

In [235]:
df_1.explode("empregos")

,nome,idade,idade_+30,altura,dobro_da_idade,soma_idade_altura,log_soma_idade_altura,Nome Completo,sobrenome,nome_upper,empregos
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo,TEO,boti
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo,TEO,via
0,Teo,28,False,182,56,210,5.347108,Teodoro Calvo,Calvo,TEO,gc
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide,Ataide,NAH,vila casa
1,Nah,30,True,165,60,195,5.273000,Natalia Ataide,Ataide,NAH,maria pia
2,Lara,27,False,170,54,197,5.283204,Lara Calvo,Calvo,LARA,sutiod artes
2,Lara,27,False,170,54,197,5.283204,Lara Calvo,Calvo,LARA,construtora
3,Pedro,25,False,176,50,201,5.303305,Pedro Silva,Silva,PEDRO,NaN
4,José,22,False,187,44,209,5.342334,José Siqueira,Siqueira,JOSÉ,NaN

## Joins

* merge com left, right, inner, etc.
* 'on' como chave

* Falar de concat

In [238]:
df_votacao.columns

Index(['ano_eleicao', 'descricao_eleicao', 'numero_turno', 'nome_partido',
       'numero_partido', 'sigla_partido', 'descricao_cargo',
       'descricao_situacao_candidatura',
       'descricao_situacao_candidatura_superior', 'nome', 'nome_social',
       'nome_urna', 'numero_sequencial', 'numero_urna', 'total_votos_ac',
       'total_votos_al', 'total_votos_am', 'total_votos_ap', 'total_votos_ba',
       'total_votos_rj', 'total_votos_sp', 'total_votos_ce', 'total_votos_ro',
       'total_votos_se', 'total_votos_pr', 'total_votos_mg', 'total_votos_mt',
       'total_votos_pe', 'total_votos_pb', 'total_votos_zz', 'total_votos_go',
       'total_votos_rs', 'total_votos_rn', 'total_votos_to', 'total_votos_pa',
       'total_votos_ms', 'total_votos_pi', 'total_votos_ma', 'total_votos_df',
       'total_votos_es', 'total_votos_rr', 'total_votos_sc', 'total_votos'],
      dtype='object')

In [243]:
df_votacao[df_votacao["nome_urna"] == "JAIR BOLSONARO"]["numero_sequencial"]

10198     190000001444
484662    280000614517
484669    280000614517
Name: numero_sequencial, dtype: int64

In [246]:
df_ben_candidato = df_bens.groupby(by=["numero_sequencial"])["valor"].sum().reset_index()

In [248]:
df_ben_candidato[ df_ben_candidato["numero_sequencial"]== 280000614517]

       numero_sequencial       valor
32899       280000614517  2286779.48

In [249]:
df_ben_candidato

       numero_sequencial       valor
0            10000000001   514392.07
1            10000000003  1579724.31
2            10000000004  2702870.00
3            10000000005    39000.00
4            10000000021   565000.00
...                  ...         ...
32910       280000624086   240000.00
32911       280000625869  7987921.57
32912       280000625870   428451.09
32913       280000629807    94590.85
32914       280000629808   428451.09

[32915 rows x 2 columns]

In [252]:
df_join = df_votacao.merge(df_ben_candidato, how="left", on="numero_sequencial")

In [6]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [256]:
df_partido_valor = df_join[ df_join["ano_eleicao"]==2018 ].groupby(by=['sigla_partido']).mean()["valor"]
df_partido_valor = df_partido_valor.reset_index()
df_partido_valor

    sigla_partido       valor
0          AVANTE  495860.124
1              DC  537424.663
2             DEM 1680155.021
3             MDB 2042179.973
4            NOVO 3187927.340
5           PATRI  455311.460
6         PC DO B  321987.860
7             PCB  156247.586
8             PCO  219191.605
9             PDT 1816419.975
10            PHS  535811.606
11            PMB  363296.618
12            PMN  588538.351
13           PODE 1388583.275
14             PP 1291253.452
15            PPL  457422.782
16            PPS  465307.028
17             PR 1141552.120
18            PRB  625356.249
19           PROS 6513199.943
20            PRP  450522.113
21           PRTB  455821.303
22            PSB 1072593.069
23            PSC  646586.363
24            PSD 1362137.237
25           PSDB 2108703.245
26            PSL  761882.662
27           PSOL  255725.290
28           PSTU  129801.460
29             PT  509515.812
30            PTB  905327.492
31            PTC  372354.493
32             PV 1319490.995
33           REDE 2330162.436
34  SOLIDARIEDADE 2052667.096

In [258]:
df_partido_valor[df_partido_valor["valor"] == df_partido_valor["valor"].max()]

   sigla_partido       valor
19          PROS 6513199.943

## Integração com banco de dados SQL

* Enviando query para o banco
* Consumindo tabela do banco
* Enviando dados para o banco

In [1]:
import sqlalchemy
import pandas as pd

con = sqlalchemy.create_engine("sqlite:///data/banco.db")

con.table_names()

['tb_bens', 'tb_candidatura', 'tb_votacao']

In [2]:
query = '''

SELECT *

FROM tb_votacao

WHERE ano_eleicao = 2018

'''

In [3]:
df_2018 = pd.read_sql_query( query, con )
df_2018

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,None,JOSE MARIA EYMAEL,...,242,1413,325,551,776,822,792,116,859,41710
1,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,None,HENRIQUE DE CAMPOS MEIRELLES,...,5324,100724,18154,16761,52214,26939,22232,3426,51670,1288950
2,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,None,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,21666,229122,90897,47974,50654,53640,79049,19231,154068,5096350
3,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,None,CIRO FERREIRA GOMES,...,54262,415593,112296,211240,282472,266272,195553,14838,264312,13344371
4,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,None,FERNANDO HADDAD,...,311212,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26445,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,None,MARCOS JOSE ROCHA DOS SANTOS,...,0,0,0,0,0,0,0,0,0,530188
26446,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,None,ANTONIO CARLOS VALADARES FILHO,...,0,0,0,0,0,0,0,0,0,370161
26447,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,None,JOAO ALBERTO RODRIGUES CAPIBERIBE,...,0,0,0,0,0,0,0,0,0,174540
26448,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,None,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,0,20497480
26449,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,None,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,0,451329,0,0,0,451329

In [7]:
query_grande = '''

SELECT t1.sigla_partido,
       sum(t2.valor) / count( distinct t1.numero_sequencial) as avg_valor

from tb_votacao as t1

left join tb_bens as t2
on t1.numero_sequencial = t2.numero_sequencial

where t1.ano_eleicao = 2018

group by t1.sigla_partido

'''

df_candidato_bens = pd.read_sql_query(query_grande, con)
df_candidato_bens

    sigla_partido   avg_valor
0          AVANTE  256710.918
1              DC  249383.236
2             DEM 1180362.072
3             MDB 1524014.905
4            NOVO 2935820.841
5           PATRI  230486.263
6         PC DO B  192423.024
7             PCB  108365.261
8             PCO   86523.002
9             PDT 1138590.198
10            PHS  291944.918
11            PMB  175759.461
12            PMN  302798.717
13           PODE  847051.963
14             PP  986014.455
15            PPL  228711.391
16            PPS  309708.358
17             PR  838515.660
18            PRB  382727.417
19           PROS 3628328.944
20            PRP  222752.582
21           PRTB  212784.973
22            PSB  775203.575
23            PSC  397714.632
24            PSD  943826.573
25           PSDB 1546713.936
26            PSL  487929.109
27           PSOL  156631.740
28           PSTU   84977.934
29             PT  369345.217
30            PTB  573222.432
31            PTC  181039.635
32             PV  845298.919
33           REDE 1534497.214
34  SOLIDARIEDADE 1258894.881

In [9]:
df_candidato_bens.to_csv("Sumarios_partido_bens.csv", index=False)
df_candidato_bens.to_excel("Sumarios_partido_bens.xlsx", index=False)

In [10]:
df_candidato_bens.to_sql("tb_bens_sumario", con, index=False)

In [11]:
con.table_names()

['tb_bens', 'tb_bens_sumario', 'tb_candidatura', 'tb_votacao']